version: '3.9'
services:
  nextapp:
    image: romanshe/nginx-with-next
    ports:
      - '80:80'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
