import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Ilus ilm on</h1>
        <h1>☀️☀️☀️</h1>

        <h2>I am the feature and want to be merged</h2>
      </main>

      <footer className={styles.footer}>Powered by Roman</footer>
    </div>
  )
}
